### ISSUE TITLE
Serve fails to run on Node 17

### ISSUE THREAD

**Issue by achou11** [small-tech/nodekit#5]
Not sure if it's a priority to support Node 17, but tried to run an example via `bin/nodekit examples/hello-count/` and ran into this error (using Node 17.5.0):

```sh
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///home/andrewchou/Code/GitHub/small-tech/nodekit//node_modules/svelte/package.json" needs an import assertion of type "json"
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loaderPaths (file:///home/andrewchou/Code/GitHub/small-tech/nodekit/lib/Utils.js:47:26)
    at async file:///home/andrewchou/Code/GitHub/small-tech/nodekit/lib/HydrationScriptCompiler.js:12:43 {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
```

Offending line seems to be here

https://github.com/small-tech/nodekit/blob/dcda50323a716419d3efaa32d01c3a30e699254e/lib/Utils.js#L47

Was able to fix that specific error locally with [this](https://github.com/tc39/proposal-import-assertions#dynamic-import), but then ran into an identical error elsewhere when re-running:

```sh
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///home/andrewchou/Code/GitHub/small-tech/nodekit/package.json" needs an import assertion of type "json"
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at new NodeError (node:internal/errors:371:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at load (file:///home/andrewchou/Code/GitHub/small-tech/nodekit/loader.js:176:10)
    at ESMLoader.load (node:internal/modules/esm/loader:359:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:280:58)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:297:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:261:34)
    at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:81:21)
    at async Promise.all (index 4)
    at async link (node:internal/modules/esm/module_job:86:9) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
```

seems to point here (or the `load` function in general?)

https://github.com/small-tech/nodekit/blob/dcda50323a716419d3efaa32d01c3a30e699254e/loader.js#L176

Patching this doesn't seem to be as trivial to me so hence this issue 😅

Command works as expected when trying with Node 16.14.0

**Comment by robertwgehl** [comment]
Same issue here on Linux 5.15.28-1 Kernel Manjaro, Node.js v17.8.0.

<pre>
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///home/robert/.small-tech.org/nodekit/app/node_modules/svelte/package.json" needs an import assertion of type "json"
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loaderPaths (file:///home/robert/.small-tech.org/nodekit/app/loader-bundle.js:26270:27)
    at async file:///home/robert/.small-tech.org/nodekit/app/loader-bundle.js:26275:58 {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}

Node.js v17.8.0
Restarting…

</pre>

**Comment by aral** [comment]
Thanks all + apologies for the slow reply.

I just merged a major refactor I was working on (that takes NodeKit from prototype to the beginnings of a maintainable app) and bumped the required minimum version to Node 18 (and added the import assertions so all’s good now) :)

Thanks again. Closing as fixed.
